/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef PROPERTYMANAGER_PROPERTYSTATE_H
#define PROPERTYMANAGER_PROPERTYSTATE_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace propertyManager {

//Enum Definition
enum class PropertyState {
    SUCCEEDED,
    FAILED,
};

inline std::string toString(PropertyState enumValue) {
    switch (enumValue) {
        case (PropertyState::SUCCEEDED):
            return "SUCCEEDED";
        case (PropertyState::FAILED):
            return "FAILED";
    }
    throw std::runtime_error("invalidPropertyStateType");
}

inline PropertyState toPropertyState(const std::string& stringValue) {
    static std::unordered_map<std::string, PropertyState> map = {
        {"SUCCEEDED", PropertyState::SUCCEEDED},
        {"FAILED", PropertyState::FAILED},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidPropertyStateType");
}

inline void to_json(nlohmann::json& j, const PropertyState& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, PropertyState& c) {
    c = toPropertyState(j);
}

}  // namespace propertyManager
}  // namespace message
}  // namespace aasb

#endif  // PROPERTYMANAGER_PROPERTYSTATE_H
