#!/bin/bash

#
# AAC pkg-config hookup
#
# 1. If PKG_CONFIG_LIBDIR is specified, and if it is located under staging
#    dir, we want to specify the staging sysroot as PKG_CONFIG_SYSROOT_DIR.
# 2. If above is not the case, and if QNX_TARGET sysenv is available, assume
#    we are QNX cross-compiling, and specify QNX sysroot as
#    PKG_CONFIG_SYSROOT_DIR.
# 3. If above is also not the case, and if SDKTARGETSYSROOT sysenv is available,
#    assume we are Linux-OE cross-compiling, and specify OE sysroot as
#    PKG_CONFIG_SYSROOT_DIR.
#

# Don't use PKG_CONFIG_PATH
export PKG_CONFIG_PATH=""

if [[ ${PKG_CONFIG_LIBDIR} == "${AAC_PKG_CONFIG_SYSROOT_DIR}"* ]]; then
	export PKG_CONFIG_SYSROOT_DIR="${AAC_PKG_CONFIG_SYSROOT_DIR}"
elif [[ ! -z ${QNX_TARGET} ]]; then
	export PKG_CONFIG_SYSROOT_DIR="${QNX_TARGET}"
elif [[ ! -z ${SDKTARGETSYSROOT} ]]; then
	export PKG_CONFIG_SYSROOT_DIR="${SDKTARGETSYSROOT}"
	export PKG_CONFIG_LIBDIR="${SDKTARGETSYSROOT}/usr/lib/pkgconfig:${SDKTARGETSYSROOT}/usr/share/pkgconfig"
fi

${AAC_PKG_CONFIG_PKG_CONFIG} $@