@startuml
skinparam roundcorner 10
participant Driver 
participant OEM_App
participant AACSTelephonyLibrary
participant AACSCoreService
participant Alexa 
Driver->Alexa: "Call Bob" / "Dial 12345"
Alexa->AACSCoreService: PhoneCallController.Dial()
AACSCoreService->AACSTelephonyLibrary: Intent(PhoneCallController.Dial)
AACSTelephonyLibrary->OEM_App: Intent(Query for PhoneAccountHandle)
OEM_App->AACSTelephonyLibrary: Intent(Reply with PhoneAccountHandle)
|||
rnote over AACSTelephonyLibrary: Initiate call with TelecomManager
loop Ongoing Call
  |||
  rnote over AACSTelephonyLibrary: Call state changes detected by \nInCallService 
  AACSTelephonyLibrary->AACSCoreService: Intent(CallStateChanged)
  AACSCoreService->Alexa: PhoneCallController.CallStateChanged()
end
@enduml