/*
 * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

#ifndef AACE_NAVIGATION_NAVIGATION_CONFIGURATION_H
#define AACE_NAVIGATION_NAVIGATION_CONFIGURATION_H

#include <string>

#include "AACE/Core/EngineConfiguration.h"

/** @file */

namespace aace {
namespace navigation {
namespace config {

/**
 * A factory interface for creating Navigation configuration objects
 */
class NavigationConfiguration {
public:
    /**
     * Factory method used to programmatically generate navigation configuration data.
     * The data generated by this method is equivalent to providing the following JSON
     * values in a configuration file:
     *
     * @code{.json}
     * {
     *   "aace.navigation": {
     *      "providerName": "<SERVICE_NAME>"
     *   }
     * }
     * @endcode
     *
     * @param [in] providerName The navigation service provider name. 
     */
    static std::shared_ptr<aace::core::config::EngineConfiguration> createNavigationConfig(
        const std::string& providerName);
};

}  // namespace config
}  // namespace navigation
}  // namespace aace

#endif  // AACE_NAVIGATION_NAVIGATION_CONFIGURATION_H
