/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef TEXTTOSPEECH_PREPARESPEECHCOMPLETEDMESSAGE_H
#define TEXTTOSPEECH_PREPARESPEECHCOMPLETEDMESSAGE_H

#include <string>
#include <vector>

#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>
#include "AASB/Message/Audio/AudioOutput/AudioStreamEncoding.h"

namespace aasb {
namespace message {
namespace textToSpeech {
namespace textToSpeech {

//Class Definition
struct PrepareSpeechCompletedMessage {
    struct Header {
        struct MessageDescription {
            static const std::string& topic() {
                static std::string topic = "TextToSpeech";
                return topic;
            }
            static const std::string& action() {
                static std::string action = "PrepareSpeechCompleted";
                return action;
            }
        };
        static const std::string& version() {
            static std::string version = "3.1";
            return version;
        }
        static const std::string& messageType() {
            static std::string messageType = "Publish";
            return messageType;
        }
        std::string id = aace::engine::utils::uuid::generateUUID();
        MessageDescription messageDescription;
    };
    struct Payload {
        using AudioStreamEncoding = ::aasb::message::audio::AudioStreamEncoding;

        static const std::string& source() {
            static std::string source = "STREAM";
            return source;
        }
        std::string speechId;
        std::string token;
        std::string streamId;
        AudioStreamEncoding encoding;
        std::unordered_map<std::string, std::string> properties;
        std::string metadata;
    };
    static const std::string& topic() {
        static std::string topic = "TextToSpeech";
        return topic;
    }
    static const std::string& action() {
        static std::string action = "PrepareSpeechCompleted";
        return action;
    }
    static const std::string& version() {
        static std::string version = "3.1";
        return version;
    }
    static const std::string& messageType() {
        static std::string messageType = "Publish";
        return messageType;
    }
    static const std::string& source() {
        static std::string source = "STREAM";
        return source;
    }
    std::string toString() const;
    Header header;
    Payload payload;
};

//JSON Serialization
inline void to_json(nlohmann::json& j, const PrepareSpeechCompletedMessage::Payload& c) {
    j = nlohmann::json{
        {"source", c.source()},
        {"speechId", c.speechId},
        {"token", c.token},
        {"streamId", c.streamId},
        {"encoding", c.encoding},
        {"properties", c.properties},
        {"metadata", c.metadata},
    };
}
inline void from_json(const nlohmann::json& j, PrepareSpeechCompletedMessage::Payload& c) {
    j.at("speechId").get_to(c.speechId);
    j.at("token").get_to(c.token);
    j.at("streamId").get_to(c.streamId);
    j.at("encoding").get_to(c.encoding);
    j.at("properties").get_to(c.properties);
    j.at("metadata").get_to(c.metadata);
}

inline void to_json(nlohmann::json& j, const PrepareSpeechCompletedMessage::Header::MessageDescription& c) {
    j = nlohmann::json{
        {"topic", c.topic()},
        {"action", c.action()},
    };
}
inline void from_json(const nlohmann::json& j, PrepareSpeechCompletedMessage::Header::MessageDescription& c) {
}

inline void to_json(nlohmann::json& j, const PrepareSpeechCompletedMessage::Header& c) {
    j = nlohmann::json{
        {"version", c.version()},
        {"messageType", c.messageType()},
        {"id", c.id},
        {"messageDescription", c.messageDescription},
    };
}
inline void from_json(const nlohmann::json& j, PrepareSpeechCompletedMessage::Header& c) {
    j.at("id").get_to(c.id);
    j.at("messageDescription").get_to(c.messageDescription);
}

inline void to_json(nlohmann::json& j, const PrepareSpeechCompletedMessage& c) {
    j = nlohmann::json{
        {"header", c.header},
        {"payload", c.payload},
    };
}
inline void from_json(const nlohmann::json& j, PrepareSpeechCompletedMessage& c) {
    j.at("header").get_to(c.header);
    j.at("payload").get_to(c.payload);
}

inline std::string PrepareSpeechCompletedMessage::toString() const {
    nlohmann::json j = *this;
    return j.dump(3);
}

}  // namespace textToSpeech
}  // namespace textToSpeech
}  // namespace message
}  // namespace aasb

#endif  // TEXTTOSPEECH_PREPARESPEECHCOMPLETEDMESSAGE_H
