#!/bin/bash

set -e

readonly SCRIPT_ROOT="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)"

format_file() {
  file="${1}"
  if [ -f $file ]; then
    ${SCRIPT_ROOT}/clang-format -style=file -i ${1}
    git add ${1}
  fi
}


case "${1}" in
  --help )
    echo "Runs clang-format on only source files"
    ;;
  * )
    for file in `git diff --cached --name-only | grep  -e  ".*\.\(h\|cpp\|c\|hpp\|java\)$"` ; do
      format_file "${file}"
    done
    ;;
esac

