@startuml

skinparam participant {
	BackgroundColor White
	ArrowColor Black
	BorderColor DarkGray
    BackgroundColor Wheat
}

participant AAOSHAL <<Android>> order 30
participant AAOSCarAPI <<Android>> order 40
participant AACS_CarControlHandler order 50
participant AACS_CarControlBroadcastReceiver order 60
participant AACS_CoreService order 70
participant AutoSDK order 80

AAOSHAL -> AAOSCarAPI : HVAC_FAN_SPEED = (0x0500|SYSTEM|3|SEAT)
AAOSCarAPI -> AACS_CarControlHandler : True/Throw Exception
AACS_CarControlHandler -> AACS_CarControlBroadcastReceiver : True/False 
AACS_CarControlBroadcastReceiver -> AACS_CoreService : Success/Failure (Intent)
AACS_CoreService -> AutoSDK : SetRangeControllerValue Reply (AASB Message)

@enduml
