@startuml

skinparam roundcorner 10

participant Application                 <<Application>> order 10
participant Connectivity                <<Platform>>    order 20
participant ConnectivityEngineImpl      <<Engine>>      order 30
participant ConnectivityCapabilityAgent <<AVS>>         order 40
participant SynchronizeState            <<AVS>>         order 50
participant ContextManager              <<AVS>>         order 60
participant ReportStateHandler          <<AVS>>         order 70
participant InternetDataPlanAPI         <<AlexaCloud>>  order 80

Application                 -> ConnectivityEngineImpl      : registerPlatformInterface()
ConnectivityEngineImpl      -> ConnectivityCapabilityAgent : create()
ConnectivityCapabilityAgent -> ContextManager              : addStateProvider(this)

... __**Application is connected to AlexaCloud**__ ...

SynchronizeState            -> ContextManager              : getContext()

...

ContextManager              -> ConnectivityCapabilityAgent : provideState()

...

ConnectivityCapabilityAgent -> ConnectivityEngineImpl      : getConnectivityState()
ConnectivityEngineImpl      -> Connectivity                : getConnectivityState()
Connectivity               --> ConnectivityEngineImpl      : ConnectivityState "{JSON}"
ConnectivityEngineImpl      -> ConnectivityCapabilityAgent : onConnectivityStateChange()
ConnectivityCapabilityAgent -> ContextManager              : executeProvideState()
ContextManager              -> ReportStateHandler          : provideStateResponse()
ReportStateHandler          -> InternetDataPlanAPI         : sendReportState()

@enduml
