/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef AUDIOOUTPUT_MEDIASTATE_H
#define AUDIOOUTPUT_MEDIASTATE_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace audio {

//Enum Definition
enum class MediaState {
    STOPPED,
    PLAYING,
    BUFFERING,
};

inline std::string toString(MediaState enumValue) {
    switch (enumValue) {
        case (MediaState::STOPPED):
            return "STOPPED";
        case (MediaState::PLAYING):
            return "PLAYING";
        case (MediaState::BUFFERING):
            return "BUFFERING";
    }
    throw std::runtime_error("invalidMediaStateType");
}

inline MediaState toMediaState(const std::string& stringValue) {
    static std::unordered_map<std::string, MediaState> map = {
        {"STOPPED", MediaState::STOPPED},
        {"PLAYING", MediaState::PLAYING},
        {"BUFFERING", MediaState::BUFFERING},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidMediaStateType");
}

inline void to_json(nlohmann::json& j, const MediaState& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, MediaState& c) {
    c = toMediaState(j);
}

}  // namespace audio
}  // namespace message
}  // namespace aasb

#endif  // AUDIOOUTPUT_MEDIASTATE_H
