@startuml

skinparam roundcorner 10
skinparam sequenceMessageAlign center
<style>
sequenceDiagram {
    .engine {
        BackgroundColor LightSkyBlue
        BorderColor CornflowerBlue
    }
    .avs {
        BackgroundColor TECHNOLOGY
        BorderColor Green
    }
}
</style>

actor Driver Order 10
participant AddressBookHandler  order 30
participant "Auto SDK"  as AutoSDK  <<engine>> order 40
participant "Alexa" as Alexa <<avs>> order 50

note right of Driver
disconnects phone from
car head unit or revokes
access
end note

Driver -> AddressBookHandler
AddressBookHandler -> AutoSDK: removeAddressBook (UNIQUE_ID)
...

AutoSDK -> Alexa: removes contacts from cloud

@enduml
