@startuml
skinparam roundcorner 10
participant Driver
participant "3P Nav App" as Nav
participant NavigationHandler
participant "Auto SDK" as SDK
participant  Alexa

Driver->SDK: "Alexa, Take me Home"


SDK-> NavigationHandler : getNavigationState()
activate NavigationHandler
NavigationHandler -->SDK : navigation context
deactivate NavigationHandler
SDK -> Alexa : Recognize event with context

Alexa->SDK : StartNavigation directive
SDK->NavigationHandler : startNavigation(payload for navigation)

NavigationHandler -> Nav : plan a route to the destination\n and start navigating
    
alt Success
	NavigationHandler <- Nav : navigation started
    NavigationHandler->SDK: navigationEvent(NAVIGATION_STARTED)
    SDK->NavigationHandler : getNavigationState()
    activate NavigationHandler
    NavigationHandler -->SDK : navigation context
	deactivate NavigationHandler
    SDK->Alexa : StartNavigationSuccess event
    Alexa->Driver : "Getting directions to home" TTS
else Error
	NavigationHandler <- Nav : navigation failed
    NavigationHandler->SDK: navigationError( NAVIGATION_START_FAILED , INTERNAL_SERVICE_ERROR , "" )
    SDK->Alexa : StartNavigationError event
    Alexa->Driver : "Sorry, cannot navigate to Home" TTS or Other error response
end
@enduml