/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef PHONECALLCONTROLLER_CALLINGDEVICECONFIGURATIONPROPERTY_H
#define PHONECALLCONTROLLER_CALLINGDEVICECONFIGURATIONPROPERTY_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace phoneCallController {

//Enum Definition
enum class CallingDeviceConfigurationProperty {
    DTMF_SUPPORTED,
};

inline std::string toString(CallingDeviceConfigurationProperty enumValue) {
    switch (enumValue) {
        case (CallingDeviceConfigurationProperty::DTMF_SUPPORTED):
            return "DTMF_SUPPORTED";
    }
    throw std::runtime_error("invalidCallingDeviceConfigurationPropertyType");
}

inline CallingDeviceConfigurationProperty toCallingDeviceConfigurationProperty(const std::string& stringValue) {
    static std::unordered_map<std::string, CallingDeviceConfigurationProperty> map = {
        {"DTMF_SUPPORTED", CallingDeviceConfigurationProperty::DTMF_SUPPORTED},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidCallingDeviceConfigurationPropertyType");
}

inline void to_json(nlohmann::json& j, const CallingDeviceConfigurationProperty& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, CallingDeviceConfigurationProperty& c) {
    c = toCallingDeviceConfigurationProperty(j);
}

}  // namespace phoneCallController
}  // namespace message
}  // namespace aasb

#endif  // PHONECALLCONTROLLER_CALLINGDEVICECONFIGURATIONPROPERTY_H
