/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef PHONECALLCONTROLLER_CALLERROR_H
#define PHONECALLCONTROLLER_CALLERROR_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace phoneCallController {

//Enum Definition
enum class CallError {
    NO_CARRIER,
    BUSY,
    NO_ANSWER,
    NO_NUMBER_FOR_REDIAL,
    OTHER,
};

inline std::string toString(CallError enumValue) {
    switch (enumValue) {
        case (CallError::NO_CARRIER):
            return "NO_CARRIER";
        case (CallError::BUSY):
            return "BUSY";
        case (CallError::NO_ANSWER):
            return "NO_ANSWER";
        case (CallError::NO_NUMBER_FOR_REDIAL):
            return "NO_NUMBER_FOR_REDIAL";
        case (CallError::OTHER):
            return "OTHER";
    }
    throw std::runtime_error("invalidCallErrorType");
}

inline CallError toCallError(const std::string& stringValue) {
    static std::unordered_map<std::string, CallError> map = {
        {"NO_CARRIER", CallError::NO_CARRIER},
        {"BUSY", CallError::BUSY},
        {"NO_ANSWER", CallError::NO_ANSWER},
        {"NO_NUMBER_FOR_REDIAL", CallError::NO_NUMBER_FOR_REDIAL},
        {"OTHER", CallError::OTHER},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidCallErrorType");
}

inline void to_json(nlohmann::json& j, const CallError& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, CallError& c) {
    c = toCallError(j);
}

}  // namespace phoneCallController
}  // namespace message
}  // namespace aasb

#endif  // PHONECALLCONTROLLER_CALLERROR_H
