@startuml

skinparam roundcorner 10

participant OEM_App order 20
participant Android_ContactsProvider order 30
participant PhoneBookController order 40
participant ContactsService order 50
participant AACSCoreService order 60
participant AutoSDK order 70
participant Alexa  order 80

... __**Removal Started by Intent**__ ...
OEM_App -> ContactsService : Intent (com.amazon.aacs.contacts.remove)
ContactsService -> ContactsService : remove(sourceId)
ContactsService -> PhoneBookController : removeAddressBook(sourceId)
PhoneBookController -> Android_ContactsProvider : query(ContactsContract)
PhoneBookController -> AACSCoreService : sendMessageReturnID(...)
AACSCoreService -> AutoSDK : publish AASBMessage(RemoveAddressBook)
AutoSDK -> Alexa : removeAddressBook(...)
AutoSDK -> AACSCoreService : receive AASBMessage(RemoveAddressBook) Reply
AACSCoreService -> ContactsService : Intent(com.amazon.aacs.aasb.RemoveAddressBook Reply)

... __**Removal Started by API Call**__ ...
OEM_App -> PhoneBookController : removeContacts(sourceId)
PhoneBookController -> PhoneBookController : removeAddressBook(sourceId)
PhoneBookController -> Android_ContactsProvider : query(ContactsContract)
PhoneBookController -> AACSCoreService : sendMessageReturnID(...)
AACSCoreService -> AutoSDK : publish AASBMessage(RemoveAddressBook)
AutoSDK -> Alexa : removeAddressBook(...)
AutoSDK -> AACSCoreService : receive AASBMessage(RemoveAddressBook) Reply
AACSCoreService -> ContactsService : Intent(com.amazon.aacs.aasb.RemoveAddressBook Reply)
ContactsService -> PhoneBookController : completeAddressBookUpdate(message.replyToId, TRUE/FALSE)
PhoneBookController -> OEM_App : removeContacts() return TRUE/FALSE
@enduml
