@startuml

skinparam roundcorner 10

participant OEM_App order 20
participant Android_ContactsProvider order 30
participant PhoneBookController order 40
participant ContactsService order 50
participant AACSCoreService order 60
participant AutoSDK  order 70
participant Alexa order 80

... __**Upload Started by Intent**__ ...
OEM_App -> ContactsService : Intent (com.amazon.aacs.contacts.upload)
ContactsService -> ContactsService : upload(sourceId, addressBookName)
ContactsService -> PhoneBookController : addAddressBook(sourceId, addressBookName)
PhoneBookController -> Android_ContactsProvider : query(ContactsContract)
PhoneBookController -> AACSCoreService : sendMessageReturnID(...)
AACSCoreService -> AutoSDK : publish AASBMessage(AddAddressBook)
AutoSDK -> Alexa : addAddressBook(...)
AutoSDK -> AACSCoreService : receive AASBMessage(AddAddressBook) Reply
AACSCoreService -> ContactsService : Intent(com.amazon.aacs.aasb.AddAddressBook Reply)

... __**Upload Started by API Call**__ ...
OEM_App -> PhoneBookController : uploadContacts(sourceId, addressBookName)
PhoneBookController -> PhoneBookController : addAddressBook(sourceId, addressBookName)
PhoneBookController -> Android_ContactsProvider : query(ContactsContract)
PhoneBookController -> AACSCoreService : sendMessageReturnID(...)
AACSCoreService -> AutoSDK : publish AASBMessage(AddAddressBook)
AutoSDK -> Alexa : addAddressBook(...)
AutoSDK -> AACSCoreService : receive AASBMessage(AddAddressBook) Reply
AACSCoreService -> ContactsService : Intent(com.amazon.aacs.aasb.AddAddressBook Reply)
ContactsService -> PhoneBookController : completeAddressBookUpdate(message.replyToId, TRUE/FALSE)
PhoneBookController -> OEM_App : uploadContacts() return TRUE/FALSE
@enduml
