@startuml

skinparam roundcorner 10

autonumber
participant Application  order 20
participant AuthorizationHandler  order 30
participant "Auto SDK" as AutoSDK  order 40

Application -> AuthorizationHandler : Canceling CBL authorization flow.
AuthorizationHandler -> AutoSDK : CancelAuthorization{ "alexa:cbl" }

AutoSDK -> AuthorizationHandler : AuthorizationStateChanged{ "alexa:cbl", UNAUTHORIZED }

@enduml
