/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef PLAYBACKCONTROLLER_PLAYBACKTOGGLE_H
#define PLAYBACKCONTROLLER_PLAYBACKTOGGLE_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace alexa {

//Enum Definition
enum class PlaybackToggle {
    SHUFFLE,
    LOOP,
    REPEAT,
    THUMBS_UP,
    THUMBS_DOWN,
};

inline std::string toString(PlaybackToggle enumValue) {
    switch (enumValue) {
        case (PlaybackToggle::SHUFFLE):
            return "SHUFFLE";
        case (PlaybackToggle::LOOP):
            return "LOOP";
        case (PlaybackToggle::REPEAT):
            return "REPEAT";
        case (PlaybackToggle::THUMBS_UP):
            return "THUMBS_UP";
        case (PlaybackToggle::THUMBS_DOWN):
            return "THUMBS_DOWN";
    }
    throw std::runtime_error("invalidPlaybackToggleType");
}

inline PlaybackToggle toPlaybackToggle(const std::string& stringValue) {
    static std::unordered_map<std::string, PlaybackToggle> map = {
        {"SHUFFLE", PlaybackToggle::SHUFFLE},
        {"LOOP", PlaybackToggle::LOOP},
        {"REPEAT", PlaybackToggle::REPEAT},
        {"THUMBS_UP", PlaybackToggle::THUMBS_UP},
        {"THUMBS_DOWN", PlaybackToggle::THUMBS_DOWN},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidPlaybackToggleType");
}

inline void to_json(nlohmann::json& j, const PlaybackToggle& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, PlaybackToggle& c) {
    c = toPlaybackToggle(j);
}

}  // namespace alexa
}  // namespace message
}  // namespace aasb

#endif  // PLAYBACKCONTROLLER_PLAYBACKTOGGLE_H
