/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef CBL_CBLSTATECHANGEDREASON_H
#define CBL_CBLSTATECHANGEDREASON_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace cbl {

//Enum Definition
enum class CBLStateChangedReason {
    SUCCESS,
    ERROR,
    TIMEOUT,
    CODE_PAIR_EXPIRED,
    AUTHORIZATION_EXPIRED,
    NONE,
};

inline std::string toString(CBLStateChangedReason enumValue) {
    switch (enumValue) {
        case (CBLStateChangedReason::SUCCESS):
            return "SUCCESS";
        case (CBLStateChangedReason::ERROR):
            return "ERROR";
        case (CBLStateChangedReason::TIMEOUT):
            return "TIMEOUT";
        case (CBLStateChangedReason::CODE_PAIR_EXPIRED):
            return "CODE_PAIR_EXPIRED";
        case (CBLStateChangedReason::AUTHORIZATION_EXPIRED):
            return "AUTHORIZATION_EXPIRED";
        case (CBLStateChangedReason::NONE):
            return "NONE";
    }
    throw std::runtime_error("invalidCBLStateChangedReasonType");
}

inline CBLStateChangedReason toCBLStateChangedReason(const std::string& stringValue) {
    static std::unordered_map<std::string, CBLStateChangedReason> map = {
        {"SUCCESS", CBLStateChangedReason::SUCCESS},
        {"ERROR", CBLStateChangedReason::ERROR},
        {"TIMEOUT", CBLStateChangedReason::TIMEOUT},
        {"CODE_PAIR_EXPIRED", CBLStateChangedReason::CODE_PAIR_EXPIRED},
        {"AUTHORIZATION_EXPIRED", CBLStateChangedReason::AUTHORIZATION_EXPIRED},
        {"NONE", CBLStateChangedReason::NONE},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidCBLStateChangedReasonType");
}

inline void to_json(nlohmann::json& j, const CBLStateChangedReason& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, CBLStateChangedReason& c) {
    c = toCBLStateChangedReason(j);
}

}  // namespace cbl
}  // namespace message
}  // namespace aasb

#endif  // CBL_CBLSTATECHANGEDREASON_H
