/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef ALEXACLIENT_CONNECTIONSTATUS_H
#define ALEXACLIENT_CONNECTIONSTATUS_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace alexa {

//Enum Definition
enum class ConnectionStatus {
    DISCONNECTED,
    PENDING,
    CONNECTED,
};

inline std::string toString(ConnectionStatus enumValue) {
    switch (enumValue) {
        case (ConnectionStatus::DISCONNECTED):
            return "DISCONNECTED";
        case (ConnectionStatus::PENDING):
            return "PENDING";
        case (ConnectionStatus::CONNECTED):
            return "CONNECTED";
    }
    throw std::runtime_error("invalidConnectionStatusType");
}

inline ConnectionStatus toConnectionStatus(const std::string& stringValue) {
    static std::unordered_map<std::string, ConnectionStatus> map = {
        {"DISCONNECTED", ConnectionStatus::DISCONNECTED},
        {"PENDING", ConnectionStatus::PENDING},
        {"CONNECTED", ConnectionStatus::CONNECTED},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidConnectionStatusType");
}

inline void to_json(nlohmann::json& j, const ConnectionStatus& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, ConnectionStatus& c) {
    c = toConnectionStatus(j);
}

}  // namespace alexa
}  // namespace message
}  // namespace aasb

#endif  // ALEXACLIENT_CONNECTIONSTATUS_H
