/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef ADDRESSBOOK_ADDADDRESSBOOKMESSAGE_H
#define ADDRESSBOOK_ADDADDRESSBOOKMESSAGE_H

#include <string>
#include <vector>

#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>
#include "AASB/Message/AddressBook/AddressBook/AddressBookType.h"
#include "AASB/Message/AddressBook/AddressBook/AddressBook.h"

namespace aasb {
namespace message {
namespace addressBook {
namespace addressBook {

//Class Definition
struct AddAddressBookMessage {
    struct Header {
        struct MessageDescription {
            static const std::string& topic() {
                static std::string topic = "AddressBook";
                return topic;
            }
            static const std::string& action() {
                static std::string action = "AddAddressBook";
                return action;
            }
        };
        static const std::string& version() {
            static std::string version = "3.0";
            return version;
        }
        static const std::string& messageType() {
            static std::string messageType = "Publish";
            return messageType;
        }
        std::string id = aace::engine::utils::uuid::generateUUID();
        MessageDescription messageDescription;
    };
    struct Payload {
        using AddressBookType = ::aasb::message::addressBook::AddressBookType;

        std::string addressBookSourceId;
        std::string name;
        AddressBookType type;
        AddressBook addressBookData;
    };
    static const std::string& topic() {
        static std::string topic = "AddressBook";
        return topic;
    }
    static const std::string& action() {
        static std::string action = "AddAddressBook";
        return action;
    }
    static const std::string& version() {
        static std::string version = "3.0";
        return version;
    }
    static const std::string& messageType() {
        static std::string messageType = "Publish";
        return messageType;
    }
    std::string toString() const;
    Header header;
    Payload payload;
};

//JSON Serialization
inline void to_json(nlohmann::json& j, const AddAddressBookMessage::Payload& c) {
    j = nlohmann::json{
        {"addressBookSourceId", c.addressBookSourceId},
        {"name", c.name},
        {"type", c.type},
        {"addressBookData", c.addressBookData},
    };
}
inline void from_json(const nlohmann::json& j, AddAddressBookMessage::Payload& c) {
    j.at("addressBookSourceId").get_to(c.addressBookSourceId);
    j.at("name").get_to(c.name);
    j.at("type").get_to(c.type);
    j.at("addressBookData").get_to(c.addressBookData);
}

inline void to_json(nlohmann::json& j, const AddAddressBookMessage::Header::MessageDescription& c) {
    j = nlohmann::json{
        {"topic", c.topic()},
        {"action", c.action()},
    };
}
inline void from_json(const nlohmann::json& j, AddAddressBookMessage::Header::MessageDescription& c) {
}

inline void to_json(nlohmann::json& j, const AddAddressBookMessage::Header& c) {
    j = nlohmann::json{
        {"version", c.version()},
        {"messageType", c.messageType()},
        {"id", c.id},
        {"messageDescription", c.messageDescription},
    };
}
inline void from_json(const nlohmann::json& j, AddAddressBookMessage::Header& c) {
    j.at("id").get_to(c.id);
    j.at("messageDescription").get_to(c.messageDescription);
}

inline void to_json(nlohmann::json& j, const AddAddressBookMessage& c) {
    j = nlohmann::json{
        {"header", c.header},
        {"payload", c.payload},
    };
}
inline void from_json(const nlohmann::json& j, AddAddressBookMessage& c) {
    j.at("header").get_to(c.header);
    j.at("payload").get_to(c.payload);
}

inline std::string AddAddressBookMessage::toString() const {
    nlohmann::json j = *this;
    return j.dump(3);
}

}  // namespace addressBook
}  // namespace addressBook
}  // namespace message
}  // namespace aasb

#endif  // ADDRESSBOOK_ADDADDRESSBOOKMESSAGE_H
