/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef ADDRESSBOOK_ADDRESSBOOKTYPE_H
#define ADDRESSBOOK_ADDRESSBOOKTYPE_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace addressBook {

//Enum Definition
enum class AddressBookType {
    CONTACT,
    NAVIGATION,
};

inline std::string toString(AddressBookType enumValue) {
    switch (enumValue) {
        case (AddressBookType::CONTACT):
            return "CONTACT";
        case (AddressBookType::NAVIGATION):
            return "NAVIGATION";
    }
    throw std::runtime_error("invalidAddressBookTypeType");
}

inline AddressBookType toAddressBookType(const std::string& stringValue) {
    static std::unordered_map<std::string, AddressBookType> map = {
        {"CONTACT", AddressBookType::CONTACT},
        {"NAVIGATION", AddressBookType::NAVIGATION},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidAddressBookTypeType");
}

inline void to_json(nlohmann::json& j, const AddressBookType& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, AddressBookType& c) {
    c = toAddressBookType(j);
}

}  // namespace addressBook
}  // namespace message
}  // namespace aasb

#endif  // ADDRESSBOOK_ADDRESSBOOKTYPE_H
