/*
 * Copyright 2017-2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amazon.aace.logger.config;

import android.util.Log;

import com.amazon.aace.core.config.EngineConfiguration;
import com.amazon.aace.core.config.StreamConfiguration;
import com.amazon.aace.logger.Logger;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;

/**
 *
 * @code{.json}
 * {
 *   "aace.logger":
 *   {
 *      "sinks": [<Sink>],
 *      "rules": [{"sink": "<SINK_ID>", "rule": <Rule>}]
 *   }
 * }
 *
 * <Sink>: {
 *   "id": "<SINK_ID>"
 *   "type": "<SINK_TYPE>",
 *   "config": {
 *     <CONFIG_DATA>
 *   },
 *   "rules": [<RuleConfiguration>]
 * }
 *
 * <Rule>: {
 *   "level": "<LOG_LEVEL>",
 *   "source": "<SOURCE_FILTER>",
 *   "tag": "<TAG_FILTER>",
 *   "message": "<MESSAGE_FILTER>"
 * }
 * @endcode
 */
public class LoggerConfiguration {

    private static final String sTag = LoggerConfiguration.class.getSimpleName();

    /**
     * Factory method used to programmatically generate logger configuration data for a console sink.
     * The data generated by this method is equivalent to providing the following JSON values
     * in a configuration file:
     *
     * @code    {.json}
     * {
     *   "aace.logger":
     *   {
     *     "sinks": [{
     *       "id": "<SINK_ID>",
     *       "type": "aace.logger.sink.console",
     *       "rules": [{
     *         "level": <LOG_LEVEL>
     *       }]
     *     }
     *   }
     * }
     * @endcode
     *
     * @param  id The id of sink object
     *
     * @param  level The log level to be used to filter logs to this sink
     */
    public static EngineConfiguration createConsoleSinkConfig( String id, Logger.Level level ) {
        EngineConfiguration consoleSinkConfig = null;

        JSONObject config = new JSONObject();
        try {
            JSONObject aaceLoggerElement = new JSONObject();

            JSONArray sinksArray = new JSONArray();

            JSONObject sinkElement = new JSONObject();
            sinkElement.put( "id", id );
            sinkElement.put( "type", "aace.logger.sink.console" );

            JSONArray rulesArray = new JSONArray();
            JSONObject ruleElement = new JSONObject();
            ruleElement.put( "level", level );
            rulesArray.put( ruleElement );
            sinkElement.put( "rules", rulesArray );

            sinksArray.put( sinkElement );
            aaceLoggerElement.put( "sinks", sinksArray );
            config.put( "aace.logger", aaceLoggerElement );

        } catch ( JSONException e ) { Log.e( sTag, e.getMessage() ); }

        String configStr = config.toString();
        try ( InputStream is = new ByteArrayInputStream(
                configStr.getBytes( StandardCharsets.UTF_8.name() ) ) )
        {
            consoleSinkConfig = StreamConfiguration.create( is );
        } catch ( IOException e ) { Log.e( sTag, e.getMessage() ); }

        return consoleSinkConfig;
    }

    /**
     * Factory method used to programmatically generate logger configuration data for a syslog sink.
     * The data generated by this method is equivalent to providing the following JSON values
     * in a configuration file:
     *
     * @code    {.json}
     * {
     *   "aace.logger":
     *   {
     *     "sinks": [{
     *       "id": "<SINK_ID>",
     *       "type": "aace.logger.sink.syslog",
     *       "rules": [{
     *         "level": <LOG_LEVEL>
     *       }]
     *     }
     *   }
     * }
     * @endcode
     *
     * @param  id The id of sink object
     *
     * @param  level The log level to be used to filter logs to this sink
     */
    public static EngineConfiguration createSyslogSinkConfig( String id, Logger.Level level ) {
        EngineConfiguration consoleSyslogSinkConfig = null;

        JSONObject config = new JSONObject();
        try {
            JSONObject aaceLoggerElement = new JSONObject();

            JSONArray sinksArray = new JSONArray();

            JSONObject sinkElement = new JSONObject();
            sinkElement.put( "id", id );
            sinkElement.put( "type", "aace.logger.sink.syslog" );

            JSONArray rulesArray = new JSONArray();
            JSONObject ruleElement = new JSONObject();
            ruleElement.put( "level", level );
            rulesArray.put( ruleElement );
            sinkElement.put( "rules", rulesArray );

            sinksArray.put( sinkElement );
            aaceLoggerElement.put( "sinks", sinksArray );
            config.put( "aace.logger", aaceLoggerElement );

        } catch ( JSONException e ) { Log.e( sTag, e.getMessage() ); }

        String configStr = config.toString();
        try ( InputStream is = new ByteArrayInputStream(
                configStr.getBytes( StandardCharsets.UTF_8.name() ) ) )
        {
            consoleSyslogSinkConfig = StreamConfiguration.create( is );
        } catch ( IOException e ) { Log.e( sTag, e.getMessage() ); }

        return consoleSyslogSinkConfig;
    }


    /**
     * Factory method used to programmatically generate logger configuration data for a file sink.
     * The data generated by this method is equivalent to providing the following JSON values
     * in a configuration file:
     *
     * @code    {.json}
     * {
     *   "aace.logger":
     *   {
     *     "sinks": [{
     *       "id": "<SINK_ID>",
     *       "type": "aace.logger.sink.file",
     *       "config": {
     *         "path": "<PATH>",
     *         "prefix": "<PREFIX>",
     *         "maxSize": <MAX_SIZE>,
     *         "maxFiles": <MAX_FILES>,
     *         "append": <APPEND>
     *       }
     *       "rules": [{
     *         "level": <LOG_LEVEL>
     *       }]
     *     }
     *   }
     * }
     * @endcode
     *
     * @param  id The id of sink object
     *
     * @param  level The log level to be used to filter logs to this sink
     *
     * @param  path The parent path where the log files will be written (must exist)
     *
     * @param  prefix The prefix name given to the log file
     *
     * @param  maxSize The maximum log file size in bytes
     *
     * @param  maxFiles The maximum number of log files to rotate
     *
     * @param  append @c true If the logs should be appended to the existing file, @c false if the file should be overwritten
     */
    public static EngineConfiguration createFileSinkConfig( String id,
                                                            Logger.Level level,
                                                            String path,
                                                            String prefix,
                                                            int maxSize,
                                                            int maxFiles,
                                                            boolean append ) {
        EngineConfiguration consoleFileSinkConfig = null;

        JSONObject config = new JSONObject();
        try {
            JSONObject aaceLoggerElement = new JSONObject();

            JSONArray sinksArray = new JSONArray();

            JSONObject sinkElement = new JSONObject();
            sinkElement.put("id", id );
            sinkElement.put( "type", "aace.logger.sink.file" );

            JSONObject configElement = new JSONObject();
            configElement.put( "path", path );
            configElement.put( "prefix", prefix );
            configElement.put( "maxSize", maxSize );
            configElement.put( "maxFiles", maxFiles );
            configElement.put( "append", append );
            sinkElement.put( "config", configElement );

            JSONArray rulesArray = new JSONArray();
            JSONObject ruleElement = new JSONObject();
            ruleElement.put( "level", level );
            rulesArray.put( ruleElement );
            sinkElement.put( "rules", rulesArray );

            sinksArray.put( sinkElement );
            aaceLoggerElement.put( "sinks", sinksArray );
            config.put( "aace.logger", aaceLoggerElement );

        } catch ( JSONException e ) { Log.e( sTag, e.getMessage() ); }

        String configStr = config.toString();
        try ( InputStream is = new ByteArrayInputStream(
                configStr.getBytes( StandardCharsets.UTF_8.name() ) ) )
        {
            consoleFileSinkConfig = StreamConfiguration.create( is );
        } catch ( IOException e ) { Log.e( sTag, e.getMessage() ); }

        return consoleFileSinkConfig;
    }

    /**
     * Factory method used to programmatically generate logger configuration data for a file sink.
     * The data generated by this method is equivalent to providing the following JSON values
     * in a configuration file:
     *
     * @code    {.json}
     * {
     *   "aace.logger":
     *   {
     *     "sinks": [{
     *       "id": "<SINK_ID>",
     *       "type": "aace.logger.sink.file",
     *       "config": {
     *         "path": "<PATH>",
     *         "prefix": "<PREFIX>",
     *         "maxSize": <MAX_SIZE>,
     *         "maxFiles": <MAX_FILES>,
     *         "append": <APPEND>
     *       }
     *       "rules": [{
     *         "level": <LOG_LEVEL>
     *       }]
     *     }
     *   }
     * }
     * @endcode
     *
     * @param  id The id of sink object
     *
     * @param  level The log level to be used to filter logs to this sink
     *
     * @param  path The parent path where the log files will be written (must exist)
     *
     * @param  prefix The prefix name given to the log file
     *
     * @param  maxSize The maximum log file size in bytes
     *
     * @param  maxFiles The maximum number of log files to rotate
     *
     * @param  append @c true If the logs should be appended to the existing file, @c false if the file should be overwritten
     */
    public static EngineConfiguration createFileSinkConfig( String id,
                                                            Logger.Level level,
                                                            String path ) {
        return createFileSinkConfig( id, level, path, "aace", 5242880, 3, true );
    }


    /**
     * Factory method used to programmatically generate configuration data for a logger rule.
     * The data generated by this method is equivalent to providing the following JSON values
     * in a configuration file:
     *
     * @code    {.json}
     * {
     *   "aace.logger":
     *   {
     *     "rules": [{
     *       "sink": "<SINK_ID>",
     *       "rule": {
     *         "level": <LOG_LEVEL>,
     *         "source": "<SOURCE_FILTER>",
     *         "tag": "<TAG_FILTER>",
     *         "message": "<MESSAGE_FILTER>"
     *       }
     *     }
     *   }
     * }
     * @endcode
     *
     * @param  sink The id of sink object to which this rule is applied
     *
     * @param  level The log level to be used as a filter for this rule
     *
     * @param  sourceFilter The source regex to be used as a filter for this rule
     *
     * @param  tagFilter The tag regex to be used as a filter for this rule
     *
     * @param  messageFilter The message regex to be used as a filter for this rule
     */
    public static EngineConfiguration createLoggerRuleConfig( String sink,
                                                              Logger.Level level,
                                                              String sourceFilter,
                                                              String tagFilter,
                                                              String messageFilter ) {
        EngineConfiguration loggerRuleConfig = null;

        JSONObject config = new JSONObject();
        try {
            JSONObject aaceLoggerElement = new JSONObject();

            JSONArray rulesArray = new JSONArray();
            JSONObject ruleTemplateElement = new JSONObject();
            ruleTemplateElement.put( "sink", sink );

            JSONObject ruleElement = new JSONObject();
            ruleElement.put( "level", level );
            ruleElement.put( "source", sourceFilter );
            ruleElement.put( "tag", tagFilter );
            ruleElement.put( "message", messageFilter );
            ruleTemplateElement.put( "rule", ruleElement );

            rulesArray.put( ruleTemplateElement );
            aaceLoggerElement.put( "rules", rulesArray );
            config.put( "aace.logger", aaceLoggerElement );

        } catch ( JSONException e ) { Log.e( sTag, e.getMessage() ); }

        String configStr = config.toString();
        try ( InputStream is = new ByteArrayInputStream(
                configStr.getBytes( StandardCharsets.UTF_8.name() ) ) )
        {
            loggerRuleConfig = StreamConfiguration.create( is );
        } catch ( IOException e ) { Log.e( sTag, e.getMessage() ); }

        return loggerRuleConfig;
    }

    /**
     * Factory method used to programmatically generate configuration data for a logger rule.
     * The data generated by this method is equivalent to providing the following JSON values
     * in a configuration file:
     *
     * @code    {.json}
     * {
     *   "aace.logger":
     *   {
     *     "rules": [{
     *       "sink": "<SINK_ID>",
     *       "rule": {
     *         "level": <LOG_LEVEL>,
     *         "source": "<SOURCE_FILTER>",
     *         "tag": "<TAG_FILTER>",
     *         "message": "<MESSAGE_FILTER>"
     *       }
     *     }
     *   }
     * }
     * @endcode
     *
     * @param  sink The id of sink object to which this rule is applied
     *
     * @param  level The log level to be used as a filter for this rule
     *
     * @param  sourceFilter The source regex to be used as a filter for this rule
     *
     * @param  tagFilter The tag regex to be used as a filter for this rule
     *
     * @param  messageFilter The message regex to be used as a filter for this rule
     */
    public static EngineConfiguration createLoggerRuleConfig( String sink, Logger.Level level ) {
        return createLoggerRuleConfig( sink, level, "", "", "" );
    }

}
