/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef EQUALIZERCONTROLLER_EQUALIZERBAND_H
#define EQUALIZERCONTROLLER_EQUALIZERBAND_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace alexa {

//Enum Definition
enum class EqualizerBand {
    BASS,
    MIDRANGE,
    TREBLE,
};

inline std::string toString(EqualizerBand enumValue) {
    switch (enumValue) {
        case (EqualizerBand::BASS):
            return "BASS";
        case (EqualizerBand::MIDRANGE):
            return "MIDRANGE";
        case (EqualizerBand::TREBLE):
            return "TREBLE";
    }
    throw std::runtime_error("invalidEqualizerBandType");
}

inline EqualizerBand toEqualizerBand(const std::string& stringValue) {
    static std::unordered_map<std::string, EqualizerBand> map = {
        {"BASS", EqualizerBand::BASS},
        {"MIDRANGE", EqualizerBand::MIDRANGE},
        {"TREBLE", EqualizerBand::TREBLE},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidEqualizerBandType");
}

inline void to_json(nlohmann::json& j, const EqualizerBand& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, EqualizerBand& c) {
    c = toEqualizerBand(j);
}

}  // namespace alexa
}  // namespace message
}  // namespace aasb

#endif  // EQUALIZERCONTROLLER_EQUALIZERBAND_H
