/*
 * Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package com.amazon.aace.navigation.config;

import com.amazon.aace.core.config.EngineConfiguration;

/**
 * A factory interface for creating Navigation configuration objects
 */
public class NavigationConfiguration {
    private static final String TAG = "NavigationConfiguration";

    /**
     * Factory method used to programmatically generate navigation configuration data.
     * The data generated by this method is equivalent to providing the following JSON
     * values in a configuration file:
     *
     * @code{.json}
     * {
     *   "aace.navigation": {
     *      "providerName": <SERVICE_NAME>
     * }
     * @endcode
     *
     * @param [in] providerName The navigation provider name
     */
    public static EngineConfiguration createNavigationConfig(final String providerName) {
        return new EngineConfiguration() {
            @Override
            protected long createNativeRef() {
                return createNavigationConfigBinder(providerName);
            }
        };
    }

    // Native Engine JNI methods
    static private native long createNavigationConfigBinder(String providerName);
}
