/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef EXTERNALMEDIAADAPTER_SESSIONSTATEEXTERNAL_H
#define EXTERNALMEDIAADAPTER_SESSIONSTATEEXTERNAL_H

#include <string>
#include <vector>

#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace alexa {

//Class Definition
struct SessionStateExternal {
    std::string toString() const;
    std::string endpointId;
    bool loggedIn;
    std::string userName;
    bool isGuest;
    bool launched;
    bool active;
    std::string accessToken;
    int64_t tokenRefreshInterval;
    std::string playerCookie;
    std::string spiVersion;
};

//JSON Serialization
inline void to_json(nlohmann::json& j, const SessionStateExternal& c) {
    j = nlohmann::json{
        {"endpointId", c.endpointId},
        {"loggedIn", c.loggedIn},
        {"userName", c.userName},
        {"isGuest", c.isGuest},
        {"launched", c.launched},
        {"active", c.active},
        {"accessToken", c.accessToken},
        {"tokenRefreshInterval", c.tokenRefreshInterval},
        {"playerCookie", c.playerCookie},
        {"spiVersion", c.spiVersion},
    };
}
inline void from_json(const nlohmann::json& j, SessionStateExternal& c) {
    j.at("endpointId").get_to(c.endpointId);
    j.at("loggedIn").get_to(c.loggedIn);
    j.at("userName").get_to(c.userName);
    j.at("isGuest").get_to(c.isGuest);
    j.at("launched").get_to(c.launched);
    j.at("active").get_to(c.active);
    j.at("accessToken").get_to(c.accessToken);
    j.at("tokenRefreshInterval").get_to(c.tokenRefreshInterval);
    j.at("playerCookie").get_to(c.playerCookie);
    j.at("spiVersion").get_to(c.spiVersion);
}

inline std::string SessionStateExternal::toString() const {
    nlohmann::json j = *this;
    return j.dump(3);
}

}  // namespace alexa
}  // namespace message
}  // namespace aasb

#endif  // EXTERNALMEDIAADAPTER_SESSIONSTATEEXTERNAL_H
