/*
 * Copyright 2017-2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef LOCATIONPROVIDER_LOCATIONSERVICEACCESS_H
#define LOCATIONPROVIDER_LOCATIONSERVICEACCESS_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace location {

//Enum Definition
enum class LocationServiceAccess {
    DISABLED,
    ENABLED,
};

inline std::string toString(LocationServiceAccess enumValue) {
    switch (enumValue) {
        case (LocationServiceAccess::DISABLED):
            return "DISABLED";
        case (LocationServiceAccess::ENABLED):
            return "ENABLED";
    }
    throw std::runtime_error("invalidLocationServiceAccessType");
}

inline LocationServiceAccess toLocationServiceAccess(const std::string& stringValue) {
    static std::unordered_map<std::string, LocationServiceAccess> map = {
        {"DISABLED", LocationServiceAccess::DISABLED},
        {"ENABLED", LocationServiceAccess::ENABLED},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidLocationServiceAccessType");
}

inline void to_json(nlohmann::json& j, const LocationServiceAccess& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, LocationServiceAccess& c) {
    c = toLocationServiceAccess(j);
}

}  // namespace location
}  // namespace message
}  // namespace aasb

#endif  // LOCATIONPROVIDER_LOCATIONSERVICEACCESS_H
