@startuml

participant User
participant App
participant AACSCoreService
participant AutoSDK
participant LoginWithAmazonService


User->App:Start Login
note right
For all intents AACSCoreService<->App

Category is com.amazon.aacs.aasb.Authorization
Action Prefix is com.amazon.aacs.aasb
Payload is JSON AASB for Authorization Interface
Refer AASB Message Documentation
end note
App->AACSCoreService:Intent-Action: StartAuthorization, for CBL
note right
Payload from Intent is sent as
JSON AASB Message to AutoSDK
end note
AACSCoreService->AutoSDK: StartAuthorization, service: alexa-cbl
opt
AutoSDK->AACSCoreService:AuthorizationStateChanged, service: <previous-service>\nUNAUTHORIZED
AACSCoreService->App: Intent-Action: AuthorizationStateChanged
end
AutoSDK->AACSCoreService:AuthorizationStateChanged, service: alexa-cbl\nAUTHORIZING
AACSCoreService->App:Intent-Action: AuthorizationStateChanged
AutoSDK->LoginWithAmazonService:Authorize and request CBL
LoginWithAmazonService->AutoSDK: CBL Code and url from LoginWithAmazon
AutoSDK->AACSCoreService:EventReceived, service: alexa-cbl\ntype:cbl-code, payload:code and url
AACSCoreService->App: Intent-Action: EventReceived
note left
App displays code
and url to user. User
authenticates code
via LoginWithAmazon
end note
AutoSDK->LoginWithAmazonService: poll for tokens
LoginWithAmazonService->AutoSDK:refresh-token, access-token received
AutoSDK->AACSCoreService:SetAuthorizationData, service: alexa-cbl\npayload: refreshtoken
AACSCoreService->App:Intent-Action: SetAuthorizationData
AutoSDK->AACSCoreService:GetAuthorizationData, service: alexa-cbl
AACSCoreService->App:Intent-Action: GetAuthorizationData
App->AACSCoreService:Intent-Action: GetAuthorizationData, stored refreshtoken
AACSCoreService->AutoSDK:GetAuthorizationData, service: alexa-cbl\npayload:refreshtoken
opt When user profile is configured in AACS
AutoSDK->AACSCoreService:EventReceived, service: alexa-cbl\ntype: user-profile, payload: name, email
AACSCoreService->App:Intent-Action: EventReceived
end
AutoSDK->AACSCoreService:AuthorizationStateChanged, service: alexa-cbl\nAUTHORIZED
AACSCoreService->App:Intent-Action: AuthorizationStateChanged
@enduml
