@startuml
skinparam roundcorner 10
skinparam sequenceMessageAlign direction

participant Driver
participant OEM_App as app
participant "Primary Bluetooth Device" as PBD
participant "BluetoothMapClient" as BMC
participant "AACSTelephonyLibrary" as ATL
participant "AACSCoreService" as Core

participant Alexa

PBD->ATL: connected
Driver->app: Consent to SMS
app->ATL: SMS allowed
ATL->Core: Intent(Messaging.UpdateMessagingEndpointState)
Core->Alexa: Messaging.UpdateMessagingEndpointState()

ATL->BMC: getUnreadMessages()
BMC->PBD: Download unread messages
loop for each unread message found
BMC->ATL: Intent(MESSAGE_RECEIVED)
ATL->ATL: Update conversation report
end
ATL->Core: Intent(Messaging.ConversationsReport)
Core->Alexa: Messaging.ConversationsReport()

Driver -> Alexa: "Alexa play my messages"
Alexa -> Driver: "Two messages from Bob"

loop Read each message from conversations report
Alexa -> Driver: "Hi how are you?"
Alexa -> Driver: "Received 5 minutes ago"
Alexa -> Core: Messaging.UpdateMessagesStatus()
Core->ATL: Intent(Messaging.UpdateMessagesStatus)

ATL->ATL: Update conversations report
ATL->BMC: updateMessageStatus()
BMC->PBD: clear unread flag

alt Success

BMC->ATL: update success
ATL->Core: Intent(Messaging.UpdateMessageSucceeded)
Core->Alexa: Messaging.UpdateMessageSucceeded()

else Failed

ATL->Core: Intent(Messaging.UpdateMessageFailed)
Core->Alexa: Messaging.UpdateMessageFailed()

end

end

Alexa->Core: Messaging.UploadConversationsReport()
Core->ATL: Intent(Messaging.UploadConversationsReport)

ATL->Core: Intent(Messaging.ConversationsReport)
Core->Alexa: Messaging.ConversationsReport()

@enduml