@startuml
skinparam roundcorner 10
participant Driver 
participant OEM_App
participant "Primary Bluetooth Device" as PBD
participant "BluetoothMapClient" as BMC
participant AACSTelephonyLibrary
participant AACSCoreService
participant Alexa 
PBD->AACSTelephonyLibrary: connected
Driver->OEM_App: Consent to SMS
OEM_App->AACSTelephonyLibrary: SMS allowed
AACSTelephonyLibrary->AACSCoreService: Intent(Messaging.UpdateMessagingEndpointState)
AACSCoreService->Alexa: Messaging.UpdateMessagingEndpointState()
Driver->Alexa: "Send a message to Bob"
Alexa->Driver: "What's the message?"
Driver->Alexa: "Good morning"
Alexa->Driver: "Your message to Bob says Good morning. Should i send it?"
Driver->Alexa: "Yes"
Alexa->Driver: "Sending SMS message to Bob"
Alexa->AACSCoreService: Messaging.SendMessage()
AACSCoreService->AACSTelephonyLibrary: Intent(Messaging.SendMessage)
AACSTelephonyLibrary->BMC: sendMessage()
BMC->PBD: sendMessage()
BMC->AACSTelephonyLibrary: send result
alt "Success"
AACSTelephonyLibrary->AACSCoreService:Intent(SendMessageSucceeded)
AACSCoreService->Alexa: Messaging.SendMessageSucceded()
else "Failed"
AACSTelephonyLibrary->AACSCoreService:Intent(SendMessageFailed)

AACSCoreService->Alexa: Messaging.SendMessageFailed()
end

@enduml