/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef APL_PROCESSACTIVITYEVENTMESSAGE_H
#define APL_PROCESSACTIVITYEVENTMESSAGE_H

#include <string>
#include <vector>

#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>
#include "AASB/Message/Apl/APL/ActivityEvent.h"

namespace aasb {
namespace message {
namespace apl {
namespace apl {

//Class Definition
struct ProcessActivityEventMessage {
    struct Header {
        struct MessageDescription {
            static const std::string& topic() {
                static std::string topic = "APL";
                return topic;
            }
            static const std::string& action() {
                static std::string action = "ProcessActivityEvent";
                return action;
            }
        };
        static const std::string& version() {
            static std::string version = "3.1";
            return version;
        }
        static const std::string& messageType() {
            static std::string messageType = "Publish";
            return messageType;
        }
        std::string id = aace::engine::utils::uuid::generateUUID();
        MessageDescription messageDescription;
    };
    struct Payload {
        using ActivityEvent = ::aasb::message::apl::ActivityEvent;

        std::string source;
        ActivityEvent event;
    };
    static const std::string& topic() {
        static std::string topic = "APL";
        return topic;
    }
    static const std::string& action() {
        static std::string action = "ProcessActivityEvent";
        return action;
    }
    static const std::string& version() {
        static std::string version = "3.1";
        return version;
    }
    static const std::string& messageType() {
        static std::string messageType = "Publish";
        return messageType;
    }
    std::string toString() const;
    Header header;
    Payload payload;
};

//JSON Serialization
inline void to_json(nlohmann::json& j, const ProcessActivityEventMessage::Payload& c) {
    j = nlohmann::json{
        {"source", c.source},
        {"event", c.event},
    };
}
inline void from_json(const nlohmann::json& j, ProcessActivityEventMessage::Payload& c) {
    j.at("source").get_to(c.source);
    j.at("event").get_to(c.event);
}

inline void to_json(nlohmann::json& j, const ProcessActivityEventMessage::Header::MessageDescription& c) {
    j = nlohmann::json{
        {"topic", c.topic()},
        {"action", c.action()},
    };
}
inline void from_json(const nlohmann::json& j, ProcessActivityEventMessage::Header::MessageDescription& c) {
}

inline void to_json(nlohmann::json& j, const ProcessActivityEventMessage::Header& c) {
    j = nlohmann::json{
        {"version", c.version()},
        {"messageType", c.messageType()},
        {"id", c.id},
        {"messageDescription", c.messageDescription},
    };
}
inline void from_json(const nlohmann::json& j, ProcessActivityEventMessage::Header& c) {
    j.at("id").get_to(c.id);
    j.at("messageDescription").get_to(c.messageDescription);
}

inline void to_json(nlohmann::json& j, const ProcessActivityEventMessage& c) {
    j = nlohmann::json{
        {"header", c.header},
        {"payload", c.payload},
    };
}
inline void from_json(const nlohmann::json& j, ProcessActivityEventMessage& c) {
    j.at("header").get_to(c.header);
    j.at("payload").get_to(c.payload);
}

inline std::string ProcessActivityEventMessage::toString() const {
    nlohmann::json j = *this;
    return j.dump(3);
}

}  // namespace apl
}  // namespace apl
}  // namespace message
}  // namespace aasb

#endif  // APL_PROCESSACTIVITYEVENTMESSAGE_H
