/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef NAVIGATION_ERRORCODE_H
#define NAVIGATION_ERRORCODE_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace navigation {
namespace navigation {

//Enum Definition
enum class ErrorCode {
    INTERNAL_SERVICE_ERROR,
    ROUTE_NOT_FOUND,
    NO_PREVIOUS_WAYPOINTS,
    NOT_SUPPORTED,
    NOT_ALLOWED,
};

inline std::string toString(ErrorCode enumValue) {
    switch (enumValue) {
        case (ErrorCode::INTERNAL_SERVICE_ERROR):
            return "INTERNAL_SERVICE_ERROR";
        case (ErrorCode::ROUTE_NOT_FOUND):
            return "ROUTE_NOT_FOUND";
        case (ErrorCode::NO_PREVIOUS_WAYPOINTS):
            return "NO_PREVIOUS_WAYPOINTS";
        case (ErrorCode::NOT_SUPPORTED):
            return "NOT_SUPPORTED";
        case (ErrorCode::NOT_ALLOWED):
            return "NOT_ALLOWED";
    }
    throw std::runtime_error("invalidErrorCodeType");
}

inline ErrorCode toErrorCode(const std::string& stringValue) {
    static std::unordered_map<std::string, ErrorCode> map = {
        {"INTERNAL_SERVICE_ERROR", ErrorCode::INTERNAL_SERVICE_ERROR},
        {"ROUTE_NOT_FOUND", ErrorCode::ROUTE_NOT_FOUND},
        {"NO_PREVIOUS_WAYPOINTS", ErrorCode::NO_PREVIOUS_WAYPOINTS},
        {"NOT_SUPPORTED", ErrorCode::NOT_SUPPORTED},
        {"NOT_ALLOWED", ErrorCode::NOT_ALLOWED},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidErrorCodeType");
}

inline void to_json(nlohmann::json& j, const ErrorCode& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, ErrorCode& c) {
    c = toErrorCode(j);
}

}  // namespace navigation
}  // namespace navigation
}  // namespace message
}  // namespace aasb

#endif  // NAVIGATION_ERRORCODE_H
