@startuml

skinparam roundcorner 10
autonumber
participant Application  order 20
participant AuthorizationHandler  order 30
participant "Auto SDK" as AutoSDK  order 40
participant LoginWithAmazonService order 50

Application -> AuthorizationHandler : Start CBL authorization using\nthe stored refresh token.
AuthorizationHandler -> AutoSDK : StartAuthorization{ "alexa:cbl", "{ "refreshToken" : "<refreshToken>" }" }
AutoSDK -> AuthorizationHandler : AuthorizationStateChanged{ "alexa:cbl", AUTHORIZING }

== Handling the refresh of tokens ==
AutoSDK -> AuthorizationHandler : GetAuthorizationData{ "alexa:cbl", "refreshToken" }
...
AutoSDK->LoginWithAmazonService: Authorize and tokens
LoginWithAmazonService-->AutoSDK: {refresh-token, access-token}
AutoSDK -> AuthorizationHandler : SetAuthorizationData{ "alexa:cbl", "refreshToken", "{ "refreshToken" : "<refreshToken>" }" }

AutoSDK -> AuthorizationHandler : AuthorizationStateChanged{ "alexa:cbl", AUTHORIZED }

@enduml
