/*
 * Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

#ifndef AACE_ADDRESS_BOOK_ADDRESS_BOOK_CONFIGURATION_H
#define AACE_ADDRESS_BOOK_ADDRESS_BOOK_CONFIGURATION_H

#include "AACE/Core/EngineConfiguration.h"

/** @file */

namespace aace {
namespace addressBook {
namespace config {

/**
 * The @c AddressBookConfiguration class is a factory interface for creating "aace.addressBook" configuration objects.
 */
class AddressBookConfiguration {
public:
    /**
     * Factory method used to programmatically generate "aace.addressBook" configuration data.
     * The data generated by this method is equivalent to providing the following JSON
     * values in a configuration file:
     *
     * @code{.json}
     * {
     *   "aace.addressBook" : {
     *      "cleanAllAddressBooksAtStart" : <true/false>
     *   }
     * }
     * @endcode
     *
     * @param [in] cleanAllAddressBooksAtStart indicates whether to clean all address books at start. The default value is @c true.
     */
    static std::shared_ptr<aace::core::config::EngineConfiguration> createAddressBookConfig(
        bool cleanAllAddressBooksAtStart = true);
};

}  // namespace config
}  // namespace addressBook
}  // namespace aace

#endif