/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef AUTHORIZATION_AUTHORIZATIONSTATE_H
#define AUTHORIZATION_AUTHORIZATIONSTATE_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace authorization {

//Enum Definition
enum class AuthorizationState {
    UNAUTHORIZED,
    AUTHORIZING,
    AUTHORIZED,
};

inline std::string toString(AuthorizationState enumValue) {
    switch (enumValue) {
        case (AuthorizationState::UNAUTHORIZED):
            return "UNAUTHORIZED";
        case (AuthorizationState::AUTHORIZING):
            return "AUTHORIZING";
        case (AuthorizationState::AUTHORIZED):
            return "AUTHORIZED";
    }
    throw std::runtime_error("invalidAuthorizationStateType");
}

inline AuthorizationState toAuthorizationState(const std::string& stringValue) {
    static std::unordered_map<std::string, AuthorizationState> map = {
        {"UNAUTHORIZED", AuthorizationState::UNAUTHORIZED},
        {"AUTHORIZING", AuthorizationState::AUTHORIZING},
        {"AUTHORIZED", AuthorizationState::AUTHORIZED},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidAuthorizationStateType");
}

inline void to_json(nlohmann::json& j, const AuthorizationState& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, AuthorizationState& c) {
    c = toAuthorizationState(j);
}

}  // namespace authorization
}  // namespace message
}  // namespace aasb

#endif  // AUTHORIZATION_AUTHORIZATIONSTATE_H
