/*
 * Copyright 2017-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

/*********************************************************
**********************************************************
**********************************************************

THIS FILE IS AUTOGENERATED. DO NOT EDIT

**********************************************************
**********************************************************
*********************************************************/

#ifndef NOTIFICATIONS_INDICATORSTATE_H
#define NOTIFICATIONS_INDICATORSTATE_H

#include <string>
#include <vector>

#include <unordered_map>
#include <AACE/Engine/Utils/UUID/UUID.h>
#include <nlohmann/json.hpp>

namespace aasb {
namespace message {
namespace alexa {

//Enum Definition
enum class IndicatorState {
    OFF,
    ON,
    UNKNOWN,
};

inline std::string toString(IndicatorState enumValue) {
    switch (enumValue) {
        case (IndicatorState::OFF):
            return "OFF";
        case (IndicatorState::ON):
            return "ON";
        case (IndicatorState::UNKNOWN):
            return "UNKNOWN";
    }
    throw std::runtime_error("invalidIndicatorStateType");
}

inline IndicatorState toIndicatorState(const std::string& stringValue) {
    static std::unordered_map<std::string, IndicatorState> map = {
        {"OFF", IndicatorState::OFF},
        {"ON", IndicatorState::ON},
        {"UNKNOWN", IndicatorState::UNKNOWN},
    };

    auto search = map.find(stringValue);
    if (search != map.end()) {
        return search->second;
    }
    throw std::runtime_error("invalidIndicatorStateType");
}

inline void to_json(nlohmann::json& j, const IndicatorState& c) {
    j = toString(c);
}

inline void from_json(const nlohmann::json& j, IndicatorState& c) {
    c = toIndicatorState(j);
}

}  // namespace alexa
}  // namespace message
}  // namespace aasb

#endif  // NOTIFICATIONS_INDICATORSTATE_H
